spring:
  main:
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: service-provider1
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.study.dubbo.provider

server:
  port: 9100